# ================= #
# BedwarsKit 配置文件 #
# ================= #

# 配置文件可能需要重载两次文件才能生效

config-version: "1.9.51"
update_checker: true
update_reportOp: true
# config-version :配置文件版本
# 不要修改，否则会重置
# update_checker : 是否检查更新
# 除非更新对你有不良影响，建议保持检查更新功能的开启状态。
# update_reportOp 向 管理员 报告 更新信息

rushWorld: "rush"
rushWorld2v2: "2v2"
rushWorld4v4: "4v4"
lobbyWorld: "lobby"
# 世界名的判断条件 最基本的配置
# 判断方式是世界名是否包含
# rushWorld : 识别为游戏房间
# rushWorld2v2 : 识别为游戏房间2v2模式
# rushWorld4v4 : 识别为游戏房间4v4模式
# lobbyWorld : 识别为大厅

relTeamName_Red: "红之队"
relTeamName_Blue: "蓝之队"
relTeamName_Green: "绿之队"
relTeamName_Yellow: "黄之队"
relTeamName_Aqua: "青之队"
relTeamName_White: "白之队"
relTeamName_Gray: "灰之队"
relTeamName_Pink: "粉之队"
# 游戏中队伍的名字 最基本的配置
# 是队伍显示名字不是颜色名字

customScoreboard: true
#是否开启 自定义计分板 功能

meanTeamBedYes: "&a✔"
meanTeamNone: "&4✘"
meanTeamBedNo: "&4✘"
meanYou: "{teamColor}⭠"
meanNotYou: "{teamColor}"
mean2v2Mode: "双人模式"
mean4v4Mode: "4v4v4v4模式"
serverIp: "&eMCBBS@the_starfish"
meanBedwars: "起床战争"
meanGameEnd: "游戏结束"
# meanTeamBedYes : ...TeamStat 中 表示队伍存在床的情况
# meanTeamNone : ...TeamStat 中 表示队伍已被淘汰
# meanTeamBedNo : ...TeamStat 中 表示队伍没有床 但 队伍存在玩家的情况
# {aliveCount} : 队伍所剩玩家
# meanYou : ...TeamIsMe 中 表示你在该队伍中，{teamColor} : 玩家当前队伍 的 队伍颜色
# meanNotYou : ...TeamIsMe 中 表示你不在该队伍中, {teamColor} : 玩家当前队伍 的 队伍颜色
# mean2v2Mode : 表示这是2v2模式
# mean4v4Mode : 表示这是4v4模式
# serverIp : 可用于填写服务器地址 ，也可以用于添加重复的字符
# meanBedwars : 可用于填写 表示起床战争 ，也可以用于添加重复的字符
# meanGameEnd : 表示游戏结束

ScoreBoard2v2Title: "&e&l{bw}"

ScoreBoard2v2Line01: "&7{date}"
ScoreBoard2v2Line02: "&e事件倒计时:&a{LastTaskTimeLeft}"
ScoreBoard2v2Line03: "&e➥{LastTaskName}"
ScoreBoard2v2Line04: "&f "
ScoreBoard2v2Line05: "{redTeamStat} &c{redTeamName} {redTeamIsMe}"
ScoreBoard2v2Line06: "{blueTeamStat} &9{blueTeamName} {blueTeamIsMe}"
ScoreBoard2v2Line07: "{greenTeamStat} &a{greenTeamName} {greenTeamIsMe}"
ScoreBoard2v2Line08: "{yellowTeamStat} &e{yellowTeamName} {yellowTeamIsMe}"
ScoreBoard2v2Line09: "{pinkTeamStat} &d{pinkTeamName} {pinkTeamIsMe}"
ScoreBoard2v2Line10: "{aquaTeamStat} &b{aquaTeamName} {aquaTeamIsMe}"
ScoreBoard2v2Line11: "{grayTeamStat} &7{grayTeamName} {grayTeamIsMe}"
ScoreBoard2v2Line12: "{whiteTeamStat} &f{whiteTeamName} {whiteTeamIsMe}"
ScoreBoard2v2Line13: "&f  "
ScoreBoard2v2Line14: "&f杀:{kill} - 死:{death} - 床:{bed}"
ScoreBoard2v2Line15: "&b{ip}"
ScoreBoard2v2Line16: ""
# 2v2模式下的 自定义计分板内容
# 变量支持的队伍名 Red(红色),Blue(蓝色),Green(绿色),Yellow(黄色),Pink(粉色),White(白色),Gray(灰色),Aqua(青色)
# 注意 : 相同的内容会被折叠成同一行，比如如果你要两行空，那么第一行需要是一个空格，第二行是两个空格
# 变量:
# ...TeamName : 队伍的名字 ,详细请看 relTeamName_...的值，队伍颜色名必须首字母小写，比如redTeamName,grayTeamName
# ...TeamStat : 队伍的状态，详细请看 meanTeam...的值 ,队伍颜色名必须首字母小写，比如greenTeamStat,grayTeamStat
# ...TeamIsMe : 你在不在该队伍，详细请看 mean...的值 ,队伍颜色名必须首字母小写，比如blueTeamIsMe,grayTeamIsMe
# ...TeamPlayer : 队伍的人数 ,队伍颜色名必须首字母小写，比如pinkTeamPlayer,grayTeamPlayer
# {formatTimeLeft} : 格式化的游戏剩余时间
# {timeleft-s} : 游戏剩余时间 - 秒
# {timeleft-m} : 游戏剩余时间 - 分钟
# {timeleft-h} : 游戏剩余时间 - 小时
# {timeleft-d} : 游戏剩余时间 - 日
# {timeleft-mo} : 游戏剩余时间 - 月
# {timeleft-y} : 游戏剩余时间 - 年
# {date} : 今天的日期 格式YYYY/M/D 比如2080/3/27
# {ip} : 配置文件里 serverIp 的值
# {bw} : 配置文件里 meanBedwars 的值
# {mode} : 配置文件里 mean...Mode 的值 如果是2v2就是 mean2v2Mode 的值，如果是4v4就是 mean4v4Mode 的值
# {kill} : 你本局中的杀敌数
# {fkill} : 你本局中的KD值
# {kd} : 你本局中的KD值
# {death} : 你本局中的死亡数
# {bed} : 你本局中的挖床数
# {game} : 本局的游戏名
# {region} : 本局的区域名
# {world} : 本局的世界名

ScoreBoard4v4Title: "&e&l{bw}"

ScoreBoard4v4Line01: "&7{date}"
ScoreBoard4v4Line02: "&e事件倒计时:&a{LastTaskTimeLeft}"
ScoreBoard4v4Line03: "&e➥{LastTaskName}"
ScoreBoard4v4Line04: "&f "
ScoreBoard4v4Line05: "{redTeamStat} &c{redTeamName} {redTeamIsMe}"
ScoreBoard4v4Line06: "{blueTeamStat} &9{blueTeamName} {blueTeamIsMe}"
ScoreBoard4v4Line07: "{greenTeamStat} &a{greenTeamName} {greenTeamIsMe}"
ScoreBoard4v4Line08: "{yellowTeamStat} &e{yellowTeamName} {yellowTeamIsMe}"
ScoreBoard4v4Line09: "&f  "
ScoreBoard4v4Line10: "&f杀:{kill} - 死:{death} - 床:{bed}"
ScoreBoard4v4Line11: "&e{ip}"
ScoreBoard4v4Line12: ""
ScoreBoard4v4Line13: ""
ScoreBoard4v4Line14: ""
ScoreBoard4v4Line15: ""
ScoreBoard4v4Line16: ""
# 4v4模式下的 自定义计分板内容
# 变量支持的队伍名 Red(红色),Blue(蓝色),Green(绿色),Yellow(黄色),Pink(粉色),White(白色),Gray(灰色),Aqua(青色)
# 注意 : 相同的内容会被折叠成同一行，比如如果你要两行空，那么第一行需要是一个空格，第二行是两个空格
# 变量:
# ...TeamName : 队伍的名字 ,详细请看 relTeamName_...的值，队伍颜色名必须首字母小写，比如redTeamName,grayTeamName
# ...TeamStat : 队伍的状态，详细请看 meanTeam...的值 ,队伍颜色名必须首字母小写，比如greenTeamStat,grayTeamStat
# ...TeamIsMe : 你在不在该队伍，详细请看 mean...的值 ,队伍颜色名必须首字母小写，比如blueTeamIsMe,grayTeamIsMe
# ...TeamPlayer : 队伍的人数 ,队伍颜色名必须首字母小写，比如pinkTeamPlayer,grayTeamPlayer
# {formatTimeLeft} : 格式化的游戏剩余时间
# {timeleft-s} : 游戏剩余时间 - 秒
# {timeleft-m} : 游戏剩余时间 - 分钟
# {timeleft-h} : 游戏剩余时间 - 小时
# {timeleft-d} : 游戏剩余时间 - 日
# {timeleft-mo} : 游戏剩余时间 - 月
# {timeleft-y} : 游戏剩余时间 - 年
# {date} : 今天的日期 格式YYYY/M/D 比如2080/3/27
# {ip} : 配置文件里 serverIp 的值
# {bw} : 配置文件里 meanBedwars 的值
# {mode} : 配置文件里 mean...Mode 的值 如果是2v2就是 mean2v2Mode 的值，如果是4v4就是 mean4v4Mode 的值
# {kill} : 你本局中的杀敌数
# {fkill} : 你本局中的KD值
# {kd} : 你本局中的KD值
# {death} : 你本局中的死亡数
# {bed} : 你本局中的挖床数
# {game} : 本局的游戏名
# {region} : 本局的区域名
# {world} : 本局的世界名


breakTitle: true
#是否开启 破坏床信息
breakTitleAll: "{BreakTeamColor}{BreakTeamName}&c的床已被摧毁"
breakSubTitleAll: "&7摧毁者:{BreakPlayerTeamColor}{BreakPlayerName}"
breakTitleBreakPlayer: "{BreakTeamColor}{BreakTeamName}"
breakSubTitleBreakPlayer: "&a床已被你摧毁"
breakTitleBreakTeam: "&c床已被摧毁"
breakSubTitleBreakTeam: "&7摧毁者:{BreakPlayerTeamColor}{BreakPlayerName}"
# All : 向 所有的玩家 发送的
# BreakPlayer : 向 破坏床的玩家 发送的
# BreakTeam : 向 被破坏床的玩家 发送的
# 变量 :
# {BreakTeamColor} : 被破坏床的队伍 的 队伍颜色
# {BreakTeamName} : 被破坏床的队伍 的 队伍名字
# {BreakPlayerTeamColor} : 破坏床的玩家 的 队伍颜色
# {BreakPlayerName} : 破坏床的玩家 的 玩家名字
# {breakPlayerTeamName} : 破坏床的玩家 的 队伍名字


deathGameMode: true
respawnDelay: 5
respawnTitle: "&e&l{timeleft}&a&l秒后复活"
respawnSubTitle: ""
respawnChat: ""
respawnActionBar: ""
respawnSuccTitle: "&f"
respawnSuccSubTitle: ""
respawnSuccChat: ""
respawnSuccActionBar: ""
preventloadworld: true
# deathGameMode : 是否开启 复活倒计时
# respawnDelay : 复活倒计时 的 时间(秒)
# respawn : 复活中
# Title : 标题
# SubTitle : 副标题
# Chat : 聊天栏 信息
# 工具栏 信息
# 变量:{timeleft} : 剩余 复活倒计时 时间(秒)
# preventloadworld : 是否开启 防止死亡后再次加载世界 需要同时关闭BedwarsRel配置文件中的die_on_void 选项

breakBedCheck: true
tpDis: 0.74
# 是否开启 防卡床
# 站在床上方破坏床时向上传送，以防止玩家卡在床里
# tpDis: 向上传送的距离，必须是double类型

noHunger: true
maxFoodLevel: 20
# noHunger : 是否开启 无饥饿
# maxFoodLevel : 要锁定的饥饿度

noPearlDamage: true
startKitCompass: false
antiDrop: true
grassPaneWalk: true
cleanBottle: true
kill_res: true
kill_res_chat: ""
NoItemBreak: true
CleanHostileOnStart: true
# noPearlDamage : 是否开启 无末影珍珠伤害
# startKitCompass : 是否开启 自动给玩家指南针
# antiDrop : 是否开启 防止移动装备
# grassPaneWalk : 是否开启 防止卡玻璃板
# cleanBottle : 是否开启 自动清理 空瓶子
# kill_res :是否开启 击杀掠夺资源
# kill_res_chat : 击杀后的提示信息，支持变
# 量 {res} : 资源名字，对应mean...的值
# {count} : 资源的所得数量
# NoItemBreak : 是否开启 禁止剑损坏
# CleanHostileOnStart 是否开启 游戏开始时删除所有敌对生物

levelupShop: true
levelupShopOpenMode: "click on item"
levelupShopOpenModeEntityName: "升级商店"
LevelupItemType: "BOOK_AND_QUILL"
LevelupItemName: "升级商店"
levelupShopDelayOpen: true
teamEnchItemName_Sharp1: "锋利I"
teamEnchItemName_Prot1: "保护I"
teamEnchItemName_Prot2: "保护II"
teamEnchItemName_Prot3: "保护III"
teamEnchItemName_Prot4: "保护IV"
meanIron: "&f铁"
meanGold: "&6金"
meanDiamond: "&b钻石"
meanEmerlad: "&a绿宝石"
shopLevelup: "升级商店"
shopItem: ""
# levelupShop :否开启 升级商店
# levelupShopOpenMode : 升级商店的打开方式，
# 支持以下模式
# "click on item" : 点击物品打开
# "click on entity" : 点击村民打开
# levelupShopOpenModeEntityName : 点击的村民的名字，需要匹配才能打开菜单
# LevelupItemType : 打开商店的 物品 的 物品类型
# levelupShopDelayOpen : 是否打开 延迟打开菜单 : 如果打开菜单的物品点击后会
# 马上打开其他物品栏，添加少许延迟以覆盖打开升级菜单
# teamEnchItemName_... : 附魔等级在菜单中的名字
# meanIron : 表示铁锭
# meanGold : 表示金锭
# meanDiamond : 表示钻石
# meanEmerlad : 表示绿宝石
# shopLevelup : 升级菜单 的 菜单标题
# shopItem : 点击物品时如果当前所在菜单的名字与这个值匹配，就打开升级菜单，一般情况下是BedwarsRel的商店
# 名(\plugins\BedwarsRel\locale\zh_CN.json : ingame.shop.name)
# 如果不需要此功能，请设置为""

sharp1Cost2v2: 4
prot1Cost2v2: 2
prot2Cost2v2: 4
prot3Cost2v2: 8
prot4Cost2v2: 16
sharp1Cost4v4: 8
prot1Cost4v4: 5
prot2Cost4v4: 10
prot3Cost4v4: 20
prot4Cost4v4: 30
#2v2 与 4v4中 附魔等级的价格
# sharp1 : 锋利1
# prot11 : 保护1


messLevelUpSharp1: "&6{player}&a购买了团队升级 &6锋利 I"
messLevelUpProt1: "&6{player}&a购买了团队升级 &6保护 I"
messLevelUpProt2: "&6{player}&a购买了团队升级 &6保护 II"
messLevelUpProt3: "&6{player}&a购买了团队升级 &6保护 III"
messLevelUpProt4: "&6{player}&a购买了团队升级 &6保护 IV"
messLevelUpFailed: "&c资源不够或已拥有更高级的附魔!"


damagefb_attackmess: true
damagefb_attackchat: ""
damagefb_attackTitle: ""
damagefb_attackSubTitle: "&3伤害 &7- &c{damage}"
damagefb_attackactionbar: ""
damagefb_attackBlood: true
damagefb_attackBloodMode: "player"
damagefb_attackBloodType: 152
# damagefb_Title : 是否开启 伤害反馈 功能
# damagefb_attackTitle : 攻击玩家时显示的 标题
# damagefb_attackSubTitle : 攻击玩家时显示的 副标题
# damagefb_attackBlood : 攻击玩家的粒子效果
# damagefb_attackBloodMode : 攻击玩家的粒子效果 显示模式,
# 支持以下模式:
# {single} : 玩家所在位置生成
# {player} : 整个玩家
# {box} : 玩家的周围
# damagefb_attackBloodType :  粒子的原理就是播放方块行走效果，
# 可以设置不同的方块以实现不同的效果，只支持数字id。默认是152:红石

killfb_sendmess: true
killfb_sendmess_chat: ""
killfb_sendmess_title: ""
killfb_sendmess_subtitle: ""
killfb_sendmess_actionbar: ""
# killfb_sendmess : 是否开启 杀敌反馈 发送信息 功能
# 支持变量:
# {dp} : 被杀的玩家 名字
# {kp} : 杀敌的玩家 名字
# {...p_health} : ...里填写d或者k，此选项代表该玩家 的 生命值

meanSecond: "秒"

upToChainArmor: "CHAINMAIL_CHESTPLATE"
upToIronArmor: "IRON_CHESTPLATE"
upToDiamondArmor: "DIAMOND_CHESTPLATE"
# 检测到物品时自动升级你的装备
# upToChainArmor : 升级到 锁链装备
# upToIronArmor : 升级到 铁装备
# upToDiamondArmor : 升级到 钻石装备
chainPriceType: "IRON_INGOT"
ironPriceType: "GOLD_INGOT"
diamondPriceType: "DIAMOND"
chainPrice: 35
ironPrice: 12
diamondPrice: 6
# 检测到你买多了装备时返还的价格 物品类型 以及 物品价格
# ...PriceType : 物品类型
# ...Price : 物品价格

kitenable: true
kitForce: false
kitForceKit: "Default"
# kitenable : 是否开启 职业功能
# kitForce : 强制设置玩家的职业，不管玩家选择了哪个职业
# kitForceKit : 强制选择的职业
# 支持以下职业:
# Default : 默认职业
# None : 无职业

kitMenuTitle: "选择职业"
kitMenurow: 6
# kitMenuTitle : 选择职业的菜单 的 菜单标题
# kitMenurow : 选择职业的菜单 的 行数 ,最多6行

kitMenuItemGive: true
kitMenuItemType: "IRON_SWORD"
kitMenuItemAmount: 1
kitMenuItemName: "选择职业"
meanSelKitSucc: "&b起床战争 &7>> &a成功选择职业!"
# kitMenuItemGive : 是否开启 自动给予 打开选择职业菜单的物品的功能
# kitMenuItemType : 打开选择职业菜单的物品 的 物品类型
# kitMenuItemAmount : 打开选择职业菜单的物品 的 物品数量
# kitMenuItemName : 打开选择职业菜单的物品 的 物品名字
# meanSelKitSucc : 成功选择职业 的 提示信息 发送在聊天栏

KitDefaultName: "默认职业"
KitDefaultDescription: "默认的职业"
KitDefaultItemType: "GOLD_HELMET"
KitDefaultItemAmount: 1
KitDefaultItemSlot: 0
KitDefaultItemName: "&f默认"
KitDefaultItemLore:
  - "&f"
  - "&a职业介绍"
  - "&f默认职业！"
  - "&f"
  - "&a职业内容"
  - "&f永久的速度"
  - "&f永久的装备"
  - "&f"
KitDefault_Boost_GiveSpeed_enable: true
KitDefault_Boost_GiveSpeed_level: 1
# Kit...Name : 职业...的名字 (目前没用)
# Kit...Description : 职业...的简介 (目前没用)
# Kit...ItemType : 职业...在选择职业菜单中的 物品类型
# Kit...ItemAmount : 职业...在选择职业菜单中的 物品数量
# Kit...ItemSlot : 职业...在选择职业菜单中的 物品位置
# Kit...ItemName : 职业...在选择职业菜单中的 物品名字
# Kit...ItemLore : 职业...在选择职业菜单中的 物品注释
# Boost_GiveSpeed_enable : 是否开启 该职业的增益效果 : 永久的速度
# Boost_GiveSpeed_level : 该职业的增益效果 : 永久的速度 的等级

KitNoneName: "无职业"
KitNoneDescription: "无的职业"
KitNoneItemType: "BARRIER"
KitNoneItemAmount: 1
KitNoneItemSlot: 1
KitNoneItemName: "&f无"
KitNoneItemLore:
  - "&f"
  - "&a职业介绍"
  - "&f无职业！"
  - "&f"
  - "&a职业内容"
  - "&f无"
  - "&f"

# Kit...Name : 职业...的名字 (目前没用)
# Kit...Description : 职业...的简介 (目前没用)
# Kit...ItemType : 职业...在选择职业菜单中的 物品类型
# Kit...ItemAmount : 职业...在选择职业菜单中的 物品数量
# Kit...ItemSlot : 职业...在选择职业菜单中的 物品位置
# Kit...ItemName : 职业...在选择职业菜单中的 物品名字
# Kit...ItemLore : 职业...在选择职业菜单中的 物品注释

KitDefaultlessName: "默认职业"
KitDefaultlessDescription: "默认的职业"
KitDefaultlessItemType: "LEATHER_HELMET"
KitDefaultlessItemAmount: 1
KitDefaultlessItemSlot: 2
KitDefaultlessItemName: "&f默认 2 "
KitDefaultlessItemLore:
  - "&f"
  - "&a职业介绍 2"
  - "&f默认职业！"
  - "&f"
  - "&a职业内容"
  - "&f永久的速度"
  - "&f永久的装备 (除了护腿和靴子)"
  - "&f"
KitDefaultless_Boost_GiveSpeed_enable: false
KitDefaultless_Boost_GiveSpeed_level: 1
# Kit...Name : 职业...的名字 (目前没用)
# Kit...Description : 职业...的简介 (目前没用)
# Kit...ItemType : 职业...在选择职业菜单中的 物品类型
# Kit...ItemAmount : 职业...在选择职业菜单中的 物品数量
# Kit...ItemSlot : 职业...在选择职业菜单中的 物品位置
# Kit...ItemName : 职业...在选择职业菜单中的 物品名字
# Kit...ItemLore : 职业...在选择职业菜单中的 物品注释
# Boost_GiveSpeed_enable : 是否开启 该职业的增益效果 : 永久的速度
# Boost_GiveSpeed_level : 该职业的增益效果 : 永久的速度 的等级


messreloadnow: "&bBedwarsKit &7>> &e正在重新加载配置文件"
messreloadsucc: "&bBedwarsKit &7>> &a成功重载配置文件"
# messreloadnow : 插件重载中 的 提示信息
# messreloadsucc : 插件已重载 的 提示信息

startmess: false
startmess_all_chat: ""
startmess_all_title: ""
startmess_all_subtitle: ""
startmess_all_actionbar: ""
# startmess : 是否开启 游戏开始时发送信息
# chat: 发送的 聊天信息
# title: 发送的 标题
# subtitle: 发送的 副标题
# actionbar: 发送的 工具栏信息

gametask: true
gametask_spawntime: true
gametask_spawntime_iron_base: 1000
gametask_spawntime_iron_1: 900
gametask_spawntime_iron_2: 750
gametask_spawntime_iron_3: 500
gametask_spawntime_iron_4: 350
gametask_spawntime_gold_base: 12000
gametask_spawntime_gold_1: 10000
gametask_spawntime_gold_2: 8000
gametask_spawntime_gold_3: 6000
gametask_spawntime_gold_4: 3000
gametask_spawntime_diamond_base: 60000
gametask_spawntime_diamond_1: 45000
gametask_spawntime_diamond_2: 30000
gametask_spawntime_diamond_3: 20000
gametask_spawntime_diamond_4: 10000
gametask_spawntime_emerald_base: 80000
gametask_spawntime_emerald_1: 65000
gametask_spawntime_emerald_2: 50000
gametask_spawntime_emerald_3: 35000
gametask_spawntime_emerald_4: 20000
gametask_boundaries_size: 9999
gametask_finalbattle: true
gametask_finalbattle_boundaries_size: 32
gametask_finalbattle_boundaries_time: 60
gametask_finalbattle_boundaries_warnidis: 0
gametask_finalbattle_boundaries_damagebuffer: 1
gametask_finalbattle_boundaries_damage: 1
# gametask : 是否启用 倒计时任务 功能
# gametask_spawntime: 是否启用 资源点调速 任务
# gametask_spawntime_..._1/2/3/4 该资源的调速级别的速度，单位毫秒
# gametask_finalbattle : 是否启用 绝杀模式 任务
# gametask_finalbattle_boundaries_size : 绝杀模式 的 世界边界 的 大小
# gametask_finalbattle_boundaries_time : 绝杀模式 的 世界边界 的 缩圈时间
# gametask_finalbattle_boundaries_warnidis : 绝杀模式 的 世界边界 的 边缘警告
# gametask_finalbattle_boundaries_damagebuffer : 绝杀模式 的 世界边界 的 伤害缓冲
# gametask_finalbattle_boundaries_damage : 绝杀模式 的 世界边界 的 伤害


gametask_spawntime_tasks_iron1: 0
gametask_spawntime_tasks_iron2: 0
gametask_spawntime_tasks_iron3: 0
gametask_spawntime_tasks_iron4: 0
gametask_spawntime_tasks_gold1: 0
gametask_spawntime_tasks_gold2: 0
gametask_spawntime_tasks_gold3: 0
gametask_spawntime_tasks_gold4: 0
gametask_spawntime_tasks_diamond1: 960
gametask_spawntime_tasks_diamond2: 1440
gametask_spawntime_tasks_diamond3: 2400
gametask_spawntime_tasks_diamond4: 3360
gametask_spawntime_tasks_emerald1: 960
gametask_spawntime_tasks_emerald2: 1920
gametask_spawntime_tasks_emerald3: 2880
gametask_spawntime_tasks_emerald4: 3848
gametask_finalbattle_time: 4328
# 任务要过多久执行，游戏开始就开始计数，单位秒
# gametask_spawntime_tasks_...1/2/3/4 : 资源任务
# gametask_finalbattle_time : 绝杀模式 任务

gametask_name_iron1: " "
gametask_name_iron2: " "
gametask_name_iron3: " "
gametask_name_iron4: " "
gametask_name_gold1: " "
gametask_name_gold2: " "
gametask_name_gold3: " "
gametask_name_gold4: " "
gametask_name_diamond1: "钻石生成提速 I"
gametask_name_diamond2: "钻石生成提速 II"
gametask_name_diamond3: "钻石生成提速 III"
gametask_name_diamond4: "钻石生成提速 IV"
gametask_name_emerald1: "绿宝石生成提速 I"
gametask_name_emerald2: "绿宝石生成提速 II"
gametask_name_emerald3: "绿宝石生成提速 III"
gametask_name_emerald4: "绿宝石生成提速 IV"
gametask_name_finalbattle: "绝杀模式"
# 此选项 暂时[[[不可用]]]
# gametask_name : 计分板中任务的名字
# gametask_name_...1/2/3/4 资源点调速等级
# gametask_name_finalbattle : 绝杀模式



# 任务完成以后发送的信息
gametask_mess_iron1_chat: ""
gametask_mess_iron1_title: ""
gametask_mess_iron1_subtitle: ""
gametask_mess_iron1_actionbar: ""
gametask_mess_iron2_chat: ""
gametask_mess_iron2_title: ""
gametask_mess_iron2_subtitle: ""
gametask_mess_iron2_actionbar: ""
gametask_mess_iron3_chat: ""
gametask_mess_iron3_title: ""
gametask_mess_iron3_subtitle: ""
gametask_mess_iron3_actionbar: ""
gametask_mess_iron4_chat: ""
gametask_mess_iron4_title: ""
gametask_mess_iron4_subtitle: ""
gametask_mess_iron4_actionbar: ""

gametask_mess_gold1_chat: ""
gametask_mess_gold1_title: ""
gametask_mess_gold1_subtitle: ""
gametask_mess_gold1_actionbar: ""
gametask_mess_gold2_chat: ""
gametask_mess_gold2_title: ""
gametask_mess_gold2_subtitle: ""
gametask_mess_gold2_actionbar: ""
gametask_mess_gold3_chat: ""
gametask_mess_gold3_title: ""
gametask_mess_gold3_subtitle: ""
gametask_mess_gold3_actionbar: ""
gametask_mess_gold4_chat: ""
gametask_mess_gold4_title: ""
gametask_mess_gold4_subtitle: ""
gametask_mess_gold4_actionbar: ""

gametask_mess_diamond1_chat: ""
gametask_mess_diamond1_title: ""
gametask_mess_diamond1_subtitle: "&4&l钻石资源点提速!"
gametask_mess_diamond1_actionbar: ""
gametask_mess_diamond2_chat: ""
gametask_mess_diamond2_title: ""
gametask_mess_diamond2_subtitle: "&4&l钻石资源点提速!"
gametask_mess_diamond2_actionbar: ""
gametask_mess_diamond3_chat: ""
gametask_mess_diamond3_title: ""
gametask_mess_diamond3_subtitle: "&4&l钻石资源点提速!"
gametask_mess_diamond3_actionbar: ""
gametask_mess_diamond4_chat: ""
gametask_mess_diamond4_title: ""
gametask_mess_diamond4_subtitle: "&4&l钻石资源点提速!"
gametask_mess_diamond4_actionbar: ""

gametask_mess_emerald1_chat: ""
gametask_mess_emerald1_title: ""
gametask_mess_emerald1_subtitle: "&4&l绿宝石资源点提速!"
gametask_mess_emerald1_actionbar: ""
gametask_mess_emerald2_chat: ""
gametask_mess_emerald2_title: ""
gametask_mess_emerald2_subtitle: "&4&l绿宝石资源点提速!"
gametask_mess_emerald2_actionbar: ""
gametask_mess_emerald3_chat: ""
gametask_mess_emerald3_title: ""
gametask_mess_emerald3_subtitle: "&4&l绿宝石资源点提速!"
gametask_mess_emerald3_actionbar: ""
gametask_mess_emerald4_chat: ""
gametask_mess_emerald4_title: ""
gametask_mess_emerald4_subtitle: "&4&l绿宝石资源点提速!"
gametask_mess_emerald4_actionbar: ""

gametask_mess_finalbattle_chat: "&f边界开始收缩，尽快前往主岛以规避伤害！"
gametask_mess_finalbattle_title: "&4&l绝杀模式"
gametask_mess_finalbattle_subtitle: "&f边界开始收缩"
gametask_mess_finalbattle_actionbar: ""

placeCorrect_ResSpawner: true
placeCorrect_ResSpawner_mess_chat: ""
placeCorrect_ResSpawner_mess_title: ""
placeCorrect_ResSpawner_mess_subtitle: ""
placeCorrect_ResSpawner_mess_actionbar: ""
# 是否开启 阻止防止方块 在资源点 功能
# ..._dis : 距离资源点的多少距离都不允许

placeCorrect_PlayerSpawnLoc: true
placeCorrect_PlayerSpawnLoc_mess_chat: "&f出生点附近禁止防止方块!"
placeCorrect_PlayerSpawnLoc_mess_title: ""
placeCorrect_PlayerSpawnLoc_mess_subtitle: ""
placeCorrect_PlayerSpawnLoc_mess_actionbar: ""
# 是否开启 阻止防止方块 在队伍出生点 功能
# ..._dis : 距离队伍出生点的多少距离都不允许

placeCorrect_notInGame: true
placeCorrect_notInGame_OpBypass: true
breakCorrect_notInGame: true
breakCorrect_notInGame_OpBypass: true
# 是否允许 在游戏外放置/破坏方块
# place :放置
# break : 破坏
# ..._OpBypass : Op是否无视这个限制