rushWorld: "rush"
rushWorld2v2: "2v2"
rushWorld4v4: "4v4"
lobbyWorld: "lobby"

relTeamName_Red: "\u7ea2\u4e4b\u961f"
relTeamName_Blue: "\u84dd\u4e4b\u961f"
relTeamName_Green: "\u7eff\u4e4b\u961f"
relTeamName_Yellow: "\u9ec4\u4e4b\u961f"
relTeamName_Aqua: "\u9752\u4e4b\u961f"
relTeamName_White: "\u767d\u4e4b\u961f"
relTeamName_Gray: "\u7070\u4e4b\u961f"
relTeamName_Pink: "\u7c89\u4e4b\u961f"