
messreloadnow: "\u6b63\u5728\u91cd\u65b0\u52a0\u8f7d\u914d\u7f6e\u6587\u4ef6"
messreloadsucc: "\u6210\u529f\u91cd\u8f7d\u914d\u7f6e\u6587\u4ef6"

grassWalk: true

sharp1Cost2v2: 4
prot1Cost2v2: 2
prot2Cost2v2: 4
prot3Cost2v2: 8
prot4Cost2v2: 16

sharp1Cost4v4: 8
prot1Cost4v4: 5
prot2Cost4v4: 10
prot3Cost4v4: 20
prot4Cost4v4: 30

LevelupItem: Material.BOOK_AND_QUILL

messLevelUpFailed: "&c\u8d44\u6e90\u4e0d\u591f\u6216\u5df2\u62e5\u6709\u66f4\u9ad8\u7ea7\u7684\u9644\u9b54!"

messLevelUpSharp1: "&6{player} &a\u8d2d\u4e70\u4e86\u56e2\u961f\u5347\u7ea7 &6\u950b\u5229 I"
messLevelUpProt1: "&6{player} &a\u8d2d\u4e70\u4e86\u56e2\u961f\u5347\u7ea7 &6\u4fdd\u62a4 I"
messLevelUpProt2: "&6{player} &a\u8d2d\u4e70\u4e86\u56e2\u961f\u5347\u7ea7 &6\u4fdd\u62a4 II"
messLevelUpProt3: "&6{player} &a\u8d2d\u4e70\u4e86\u56e2\u961f\u5347\u7ea7 &6\u4fdd\u62a4 III"
messLevelUpProt4: "&6{player} &a\u8d2d\u4e70\u4e86\u56e2\u961f\u5347\u7ea7 &6\u4fdd\u62a4 IV"
meanDiamond: "&b\u94bb\u77f3"
shopItem: "\u7269\u54c1\u5546\u5e97"
shopLevelup: "\u5347\u7ea7\u5546\u5e97"
teamEnchItemName_Sharp1: "\u950b\u5229 I"
teamEnchItemName_Prot1: "\u4fdd\u62a4 I"
teamEnchItemName_Prot2: "\u4fdd\u62a4 II"
teamEnchItemName_Prot3: "\u4fdd\u62a4 III"
teamEnchItemName_Prot4: "\u4fdd\u62a4 IV"

kill_res: true
dateDisplay: "&7{date}"
relTeamColorName_Red: "\u7ea2\u4e4b\u961f"
relTeamColorName_Blue: "\u84dd\u4e4b\u961f"
relTeamColorName_Green: "\u7eff\u4e4b\u961f"
relTeamColorName_Yellow: "\u9ec4\u4e4b\u961f"
relTeamColorName_Aqua: "\u9752\u4e4b\u961f"
relTeamColorName_White: "\u767d\u4e4b\u961f"
relTeamColorName_Gray: "\u7070\u4e4b\u961f"
relTeamColorName_Pink: "\u7c89\u4e4b\u961f"
rushModeSpeedLevel: 1
rushModeSpeed: true
breakTitle: true
breakTitleAll: "{BreakTeamColor}{BreakTeamName}&c\u7684\u5e8a\u5df2\u88ab\u6467\u6bc1"
breakSubTitleAll: "&7\u6467\u6bc1\u8005:{BreakPlayerTeamColor}{BreakPlayerName}"
breakTitleBreakPlayer: "{BreakTeamColor}{BreakTeamName}"
breakSubTitleBreakPlayer: "&a\u5e8a\u5df2\u88ab\u4f60\u6467\u6bc1"
breakTitleBreakTeam: "&c\u5e8a\u5df2\u88ab\u6467\u6bc1"
breakSubTitleBreakTeam: "&7\u6467\u6bc1\u8005:{BreakPlayerTeamColor}{BreakPlayerName}"
noHunger: true
maxFoodLevel: 20
noPearlDamage: true
breakBedCheck: true
tpDis: 0.74
deathGameMode: true
rushWorld: "rush"
rushWorld2v2: "2v2rush"
rushWorld4v4: "4v4rush"
lobbyWorld: "lobby"
startKitCompass: false
respawnDelay: 5
respawnTitle: "&e{timeleft}&a\u79d2\u540e\u590d\u6d3b"
respawnSubTitle: " "
respawnSuccTitle: "&a\u5df2\u56de\u57ce"
respawnSuccSubTitle: " "
customScoreboard: true
scoreboardTitle: "&e\u8d77\u5e8a\u6218\u4e89"
antiDrop: true
meanTeamBedYes: "&a&l\u2714"
meanTeamNone: "&c&l\u2718"
meanTeamBedNo: "{aliveCount}"
serverIp: "&eMCBBS@the_starfish"
meanYou: "{teamColor}\u2192 "
meanNotYou: "  "