# ================= #
# BedwarsKit 配置文件 #
# ================= #

# 目前出于未知原因，需要重载两次文件才能生效

config-version: "1.9.5"
# 配置文件版本
# 无需更改

rushWorld: "rush"
rushWorld2v2: "2v2rush"
rushWorld4v4: "4v4rush"
lobbyWorld: "lobby"
# 世界名的判断条件 最基本的配置
# 判断方式是世界名是否包含
# rushWorld : 识别为游戏房间
# rushWorld2v2 : 识别为游戏房间2v2模式
# rushWorld4v4 : 识别为游戏房间4v4模式
# lobbyWorld : 识别为大厅

relTeamName_Red: "红之队"
relTeamName_Blue: "蓝之队"
relTeamName_Green: "绿之队"
relTeamName_Yellow: "黄之队"
relTeamName_Aqua: "青之队"
relTeamName_White: "白之队"
relTeamName_Gray: "灰之队"
relTeamName_Pink: "粉之队"
# 游戏中队伍的名字 最基本的配置
# 是队伍显示名字不是颜色名字

customScoreboard: true
#是否开启 自定义计分板 功能

meanTeamBedYes: "&a✔"
meanTeamNone: "&c✘"
meanTeamBedNo: "&c✘"
meanYou: "{teamColor}→ "
meanNotYou: "{teamColor}  "
mean2v2Mode: "双人模式"
mean4v4Mode: "4v4v4v4模式"
serverIp: "&eMCBBS@the_starfish"
meanBedwars: "起床战争"
# meanTeamBedYes : ...TeamStat 中 表示队伍存在床的情况
# meanTeamNone : ...TeamStat 中 表示队伍已被淘汰
# meanTeamBedNo : ...TeamStat 中 表示队伍没有床 但 队伍存在玩家的情况
# meanYou : ...TeamIsMe 中 表示你在该队伍中，{teamColor} : 玩家当前队伍 的 队伍颜色
# meanNotYou : ...TeamIsMe 中 表示你不在该队伍中, {teamColor} : 玩家当前队伍 的 队伍颜色
# mean2v2Mode : 表示这是2v2模式
# mean4v4Mode : 表示这是4v4模式
# serverIp : 可用于填写服务器地址 ，也可以用于添加重复的字符
# meanBedwars : 可用于填写 表示起床战争 ，也可以用于添加重复的字符

ScoreBoard2v2Title: "&e&l{bw}"

ScoreBoard2v2Line01: "&7{date} &8{mode}"
ScoreBoard2v2Line02: "&a{timeleft-s}&f秒之后&b游戏结束"
ScoreBoard2v2Line03: "&f"
ScoreBoard2v2Line04: "{redTeamIsMe}&c{RedTeamName} {redTeamStat} &7(&f&l{redTeamPlayer}&7)"
ScoreBoard2v2Line05: "{blueTeamIsMe}&9{BlueTeamName} {blueTeamStat} &7(&f&l{blueTeamPlayer}&7)"
ScoreBoard2v2Line06: "{greenTeamIsMe}&a{GreenTeamName} {greenTeamStat} &7(&f&l{greenTeamPlayer}&7)"
ScoreBoard2v2Line07: "{yellowTeamIsMe}&e{YellowTeamName} {yellowTeamStat} &7(&f&l{yellowTeamPlayer}&7)"
ScoreBoard2v2Line08: "{pinkTeamIsMe}&d{PinkTeamName} {pinkTeamStat} &7(&f&l{pinkTeamPlayer}&7)"
ScoreBoard2v2Line09: "{aquaTeamIsMe}&b{AquaTeamName} {aquaTeamStat} &7(&f&l{aquaTeamPlayer}&7)"
ScoreBoard2v2Line10: "{grayTeamIsMe}&7{GrayTeamName} {grayTeamStat} &7(&f&l{grayTeamPlayer}&7)"
ScoreBoard2v2Line11: "{whiteTeamIsMe}&f{WhiteTeamName} {whiteTeamStat} &7(&f&l{whiteTeamPlayer}&7)"
ScoreBoard2v2Line12: "&f "
ScoreBoard2v2Line13: "&e{ip}"
ScoreBoard2v2Line14: ""
ScoreBoard2v2Line15: ""
ScoreBoard2v2Line16: ""
# 2v2模式下的 自定义计分板内容
# 变量支持的队伍名 Red(红色),Blue(蓝色),Green(绿色),Yellow(黄色),Pink(粉色),White(白色),Gray(灰色),Aqua(青色)
# 变量:
# ...TeamName : 队伍的名字 ,详细请看 relTeamName_...的值，队伍颜色名必须首字母大写，比如RedTeamName,GrayTeamName
# ...TeamStat : 队伍的状态，详细请看 meanTeam...的值 ,队伍颜色名必须首字母小写，比如greenTeamStat,grayTeamStat
# ...TeamIsMe : 你在不在该队伍，详细请看 mean...的值 ,队伍颜色名必须首字母小写，比如blueTeamIsMe,grayTeamIsMe
# ...TeamPlayer : 队伍的人数 ,队伍颜色名必须首字母小写，比如pinkTeamPlayer,grayTeamPlayer
# {timeleft-s} : 游戏剩余时间 - 秒
# {timeleft-m} : 游戏剩余时间 - 分钟
# {timeleft-h} : 游戏剩余时间 - 小时
# {timeleft-d} : 游戏剩余时间 - 日
# {timeleft-mo} : 游戏剩余时间 - 月
# {timeleft-y} : 游戏剩余时间 - 年
# {date} : 今天的日期 格式YYYY/M/D 比如2080/3/27
# {ip} : 配置文件里 serverIp 的值
# {bw} : 配置文件里 meanBedwars 的值
# {mode} : 配置文件里 mean...Mode 的值 如果是2v2就是 mean2v2Mode 的值，如果是4v4就是 mean4v4Mode 的值
# {kill} : 你本局中的杀敌数
# {fkill} : 你本局中的KD值
# {kd} : 你本局中的KD值
# {death} : 你本局中的死亡数
# {bed} : 你本局中的挖床数
# {game} : 本局的游戏名
# {region} : 本局的区域名
# {world} : 本局的世界名

ScoreBoard4v4Title: "&e&l{bw}"

ScoreBoard4v4Line01: "&7{date} &8{mode}"
ScoreBoard4v4Line02: "&a{timeleft-s}&f秒之后&b游戏结束"
ScoreBoard4v4Line03: "&f"
ScoreBoard4v4Line04: "{redTeamIsMe}&c{RedTeamName} {redTeamStat} &7(&f&l{redTeamPlayer}&7)"
ScoreBoard4v4Line05: "{blueTeamIsMe}&9{BlueTeamName} {blueTeamStat} &7(&f&l{blueTeamPlayer}&7)"
ScoreBoard4v4Line06: "{greenTeamIsMe}&a{GreenTeamName} {greenTeamStat} &7(&f&l{greenTeamPlayer}&7)"
ScoreBoard4v4Line07: "{yellowTeamIsMe}&e{YellowTeamName} {yellowTeamStat} &7(&f&l{yellowTeamPlayer}&7)"
ScoreBoard4v4Line08: "&f "
ScoreBoard4v4Line09: "&f\u51fb\u6740\u6570: &a{kill}"
ScoreBoard4v4Line10: "&f\u7834\u574f\u5e8a\u6570: &a{bed}"
ScoreBoard4v4Line11: "&f\u6700\u7ec8\u51fb\u6740\u6570: &a{fkill}"
ScoreBoard4v4Line12: "&f  "
ScoreBoard4v4Line13: "&e{ip}"
ScoreBoard4v4Line14: ""
ScoreBoard4v4Line15: ""
ScoreBoard4v4Line16: ""
# 4v4模式下的 自定义计分板内容
# 变量支持的队伍名 Red(红色),Blue(蓝色),Green(绿色),Yellow(黄色),Pink(粉色),White(白色),Gray(灰色),Aqua(青色)
# 变量:
# ...TeamName : 队伍的名字 ,详细请看 relTeamName_...的值，队伍颜色名必须首字母大写，比如RedTeamName,GrayTeamName
# ...TeamStat : 队伍的状态，详细请看 meanTeam...的值 ,队伍颜色名必须首字母小写，比如greenTeamStat,grayTeamStat
# ...TeamIsMe : 你在不在该队伍，详细请看 mean...的值 ,队伍颜色名必须首字母小写，比如blueTeamIsMe,grayTeamIsMe
# ...TeamPlayer : 队伍的人数 ,队伍颜色名必须首字母小写，比如pinkTeamPlayer,grayTeamPlayer
# {timeleft-s} : 游戏剩余时间 - 秒
# {timeleft-m} : 游戏剩余时间 - 分钟
# {timeleft-h} : 游戏剩余时间 - 小时
# {timeleft-d} : 游戏剩余时间 - 日
# {timeleft-mo} : 游戏剩余时间 - 月
# {timeleft-y} : 游戏剩余时间 - 年
# {date} : 今天的日期 格式YYYY/M/D 比如2080/3/27
# {ip} : 配置文件里 serverIp 的值
# {bw} : 配置文件里 meanBedwars 的值
# {mode} : 配置文件里 mean...Mode 的值 如果是2v2就是 mean2v2Mode 的值，如果是4v4就是 mean4v4Mode 的值
# {kill} : 你本局中的杀敌数
# {fkill} : 你本局中的KD值
# {kd} : 你本局中的KD值
# {death} : 你本局中的死亡数
# {bed} : 你本局中的挖床数
# {game} : 本局的游戏名
# {region} : 本局的区域名
# {world} : 本局的世界名


breakTitle: true
#是否开启 破坏床信息
breakTitleAll: "{BreakTeamColor}{BreakTeamName}&c的床已被摧毁"
breakSubTitleAll: "&7摧毁者:{BreakPlayerTeamColor}{BreakPlayerName}"
breakTitleBreakPlayer: "{BreakTeamColor}{BreakTeamName}"
breakSubTitleBreakPlayer: "&a床已被你摧毁"
breakTitleBreakTeam: "&c床已被摧毁"
breakSubTitleBreakTeam: "&7摧毁者:{BreakPlayerTeamColor}{BreakPlayerName}"
# All : 向 所有的玩家 发送的
# BreakPlayer : 向 破坏床的玩家 发送的
# BreakTeam : 向 被破坏床的玩家 发送的
# 变量 :
# {BreakTeamColor} : 被破坏床的队伍 的 队伍颜色
# {BreakTeamName} : 被破坏床的队伍 的 队伍名字
# {BreakPlayerTeamColor} : 破坏床的玩家 的 队伍颜色
# {BreakPlayerName} : 破坏床的玩家 的 玩家名字
# {breakPlayerTeamName} : 破坏床的玩家 的 队伍名字


deathGameMode: true
respawnDelay: 5
respawnTitle: "&e&l{timeleft}&a&l秒后复活"
respawnSubTitle: ""
respawnSuccTitle: "&f"
respawnSuccSubTitle: ""
# deathGameMode : 是否开启 复活倒计时
# respawnDelay : 复活倒计时 的 时间(秒)
# respawnTitle : 复活中 的 标题，
# 变量:{timeleft} : 剩余时间(秒)
# respawnSubTitle : 复活中 的 副标题，
# 变量:{timeleft} : 剩余时间(秒)
# respawnSuccTitle : 已复活 的 标题
# respawnSuccSubTitle : 已复活 的 副标题

breakBedCheck: true
tpDis: 0.74
# 是否开启 防卡床
# 站在床上方破坏床时向上传送，以防止玩家卡在床里
# tpDis: 向上传送的距离，必须是double类型

noHunger: true
maxFoodLevel: 20
# noHunger : 是否开启 无饥饿
# maxFoodLevel : 要锁定的饥饿度

noPearlDamage: true
startKitCompass: false
antiDrop: true
grassPaneWalk: true
cleanBottle: true
kill_res: true
NoItemBreak: true
# noPearlDamage : 是否开启 无末影珍珠伤害
# startKitCompass : 是否开启 自动给玩家指南针
# antiDrop : 是否开启 防止移动装备
# grassPaneWalk : 是否开启 防止卡玻璃板
# cleanBottle : 是否开启 自动清理 空瓶子
# kill_res :是否开启 击杀掠夺资源
# NoItemBreak : 是否开启 禁止剑损坏

levelupShop: true
levelupShopOpenMode: "click on item"
levelupShopOpenModeEntityName: "升级商店"
LevelupItemType: "BOOK_AND_QUILL"
levelupShopDelayOpen: true
teamEnchItemName_Sharp1: "锋利I"
teamEnchItemName_Prot1: "保护I"
teamEnchItemName_Prot2: "保护II"
teamEnchItemName_Prot3: "保护III"
teamEnchItemName_Prot4: "保护IV"
meanDiamond: "&b\u94bb\u77f3"
shopLevelup: "\u5347\u7ea7\u5546\u5e97"
shopItem: "\u5546\u5e97"
# levelupShop :否开启 升级商店
# levelupShopOpenMode : 升级商店的打开方式，
# 支持以下模式
# "click on item" : 点击物品打开
# "click on entity" : 点击村民打开
# levelupShopOpenModeEntityName : 点击的村民的名字，需要匹配才能打开菜单
# LevelupItemType : 打开商店的 物品 的 物品类型
# levelupShopDelayOpen : 是否打开 延迟打开菜单 : 如果打开菜单的物品点击后会
# 马上打开其他物品栏，添加少许延迟以覆盖打开升级菜单
# teamEnchItemName_... : 附魔等级在菜单中的名字
# meanDiamond : 表示钻石
# shopLevelup : 升级菜单 的 菜单标题
# shopItem : 点击物品时如果当前所在菜单的名字与这个值匹配，就打开升级菜单，一般情况下是BedwarsRel的商店名(\plugins\BedwarsRel\locale\zh_CN.json : ingame.shop.name)

sharp1Cost2v2: 4
prot1Cost2v2: 2
prot2Cost2v2: 4
prot3Cost2v2: 8
prot4Cost2v2: 16
sharp1Cost4v4: 8
prot1Cost4v4: 5
prot2Cost4v4: 10
prot3Cost4v4: 20
prot4Cost4v4: 30
#2v2 与 4v4中 附魔等级的价格
# sharp1 : 锋利1
# prot11 : 保护1


messLevelUpSharp1: "&6{player}&a购买了团队升级&6锋利I"
messLevelUpProt1: "&6{player}&a购买了团队升级&6保护I"
messLevelUpProt2: "&6{player}&a购买了团队升级&6保护II"
messLevelUpProt3: "&6{player}&a购买了团队升级&6保护III"
messLevelUpProt4: "&6{player}&a购买了团队升级&6保护IV"
messLevelUpFailed: "&c资源不够或已拥有更高级的附魔!"


damagefb_Title: true
damagefb_attackTitle: ""
damagefb_attackSubTitle: "&3伤害 &7- &c{damage}"
damagefb_attackBlood: true
damagefb_attackBloodMode: "box"
# damagefb_Title : 是否开启 伤害反馈 功能
# damagefb_attackTitle : 攻击玩家时显示的 标题
# damagefb_attackSubTitle : 攻击玩家时显示的 副标题
# damagefb_attackBlood : 攻击玩家的粒子效果
# damagefb_attackBloodMode : 攻击玩家的粒子效果 显示模式,
# 支持以下模式:
# {single} : 玩家所在位置生成
# {player} : 整个玩家
# {box} : 玩家的周围

upToChainArmor: "CHAINMAIL_CHESTPLATE"
upToIronArmor: "IRON_CHESTPLATE"
upToDiamondArmor: "DIAMOND_CHESTPLATE"
# 检测到物品时自动升级你的装备
# upToChainArmor : 升级到 锁链装备
# upToIronArmor : 升级到 铁装备
# upToDiamondArmor : 升级到 钻石装备
chainPriceType: "IRON_INGOT"
ironPriceType: "GOLD_INGOT"
diamondPriceType: "DIAMOND"
chainPrice: 35
ironPrice: 12
diamondPrice: 6
# 检测到你买多了装备时返还的价格 物品类型 以及 物品价格
# ...PriceType : 物品类型
# ...Price : 物品价格

kitenable: true
kitForce: false
kitForceKit: "Default"
# kitenable : 是否开启 职业功能
# kitForce : 强制设置玩家的职业，不管玩家选择了哪个职业
# kitForceKit : 强制选择的职业
# 支持以下职业:
# Default : 默认职业
# None : 无职业

kitMenuTitle: "选择职业"
kitMenurow: 6
# kitMenuTitle : 选择职业的菜单 的 菜单标题
# kitMenurow : 选择职业的菜单 的 行数 ,最多6行

kitMenuItemGive: true
kitMenuItemType: "IRON_SWORD"
kitMenuItemAmount: 1
kitMenuItemName: "\u9009\u62e9\u804c\u4e1a"
meanSelKitSucc: "&a\u6210\u529f\u9009\u62e9\u804c\u4e1a!"
# kitMenuItemGive : 是否开启 自动给予 打开选择职业菜单的物品的功能
# kitMenuItemType : 打开选择职业菜单的物品 的 物品类型
# kitMenuItemAmount : 打开选择职业菜单的物品 的 物品数量
# kitMenuItemName : 打开选择职业菜单的物品 的 物品名字
# meanSelKitSucc : 成功选择职业 的 提示信息 发送在聊天栏

KitDefaultName: "默认职业"
KitDefaultDescription: "默认的职业"
KitDefaultItemType: "GOLD_HELMET"
KitDefaultItemAmount: 1
KitDefaultItemSlot: 0
KitDefaultItemName: "&f默认"
KitDefaultItemLore:
  - "&f"
  - "&a职业介绍"
  - "&f默认职业！"
  - "&f"
  - "&a职业内容"
  - "&f永久的速度"
  - "&f永久的装备"
  - "&f"
KitDefault_Boost_GiveSpeed_enable: true
KitDefault_Boost_GiveSpeed_level: 1
# Kit...Name : 职业...的名字 (目前没用)
# Kit...Description : 职业...的简介 (目前没用)
# Kit...ItemType : 职业...在选择职业菜单中的 物品类型
# Kit...ItemAmount : 职业...在选择职业菜单中的 物品数量
# Kit...ItemSlot : 职业...在选择职业菜单中的 物品位置
# Kit...ItemName : 职业...在选择职业菜单中的 物品名字
# Kit...ItemLore : 职业...在选择职业菜单中的 物品注释
# KitDefault_Boost_GiveSpeed_enable : 是否开启 该职业的增益效果 : 永久的速度
# KitDefault_Boost_GiveSpeed_level : 该职业的增益效果 : 永久的速度 的等级

KitNoneName: "无职业"
KitNoneDescription: "无的职业"
KitNoneItemType: "BARRIER"
KitNoneItemAmount: 1
KitNoneItemSlot: 1
KitNoneItemName: "&f无"
KitNoneItemLore:
  - "&f"
  - "&a职业介绍"
  - "&f无职业！"
  - "&f"
  - "&a职业内容"
  - "&f无"
  - "&f"

# Kit...Name : 职业...的名字 (目前没用)
# Kit...Description : 职业...的简介 (目前没用)
# Kit...ItemType : 职业...在选择职业菜单中的 物品类型
# Kit...ItemAmount : 职业...在选择职业菜单中的 物品数量
# Kit...ItemSlot : 职业...在选择职业菜单中的 物品位置
# Kit...ItemName : 职业...在选择职业菜单中的 物品名字
# Kit...ItemLore : 职业...在选择职业菜单中的 物品注释

messreloadnow: "正在重新加载配置文件"
messreloadsucc: "成功重载配置文件"
# messreloadnow : 插件重载中 的 提示信息
# messreloadsucc : 插件已重载 的 提示信息

startmess: false
startmess_all_chat: ""
startmess_all_title: ""
startmess_all_subtitle: ""
# startmess : 是否开启 游戏开始时发送信息
# chat: 发送的 聊天信息
# title: 发送的 标题
# subtitle: 发送的 副标题