name: BedwarsKit
version: 1.9.54
main: github.tsffish.bedwarskit.Main
author: tsffish
api-version: 1.13
commands:
  bwk:
    description: Hello Command
    usage: /bwk
  bwk reload:
    description: Reload Command
    usage: /bwk reload
