name: BedwarsKit
version: 1.9.56
main: github.tsffish.bedwarskit.BedwarsKit
author: Tsffish
api-version: 1.13
depend:
  - BedwarsRel
  - ProtocolLib
commands:
  bwk:
    description: Hello Command
    usage: /bwk
  bwk reload:
    description: Reload Command
    usage: /bwk reload
